// Structured front-matter content for the copyright and usage pages.
// Lemma ships a single unified edition; this file holds the defaults and
// accepts a JSON override file that deep-merges on top of them.

use serde_json::{Map, Value, json};
use std::fs;
use std::path::{Path, PathBuf};

pub type FrontMatter = Value;

pub fn default_front_matter() -> Value {
    json!({
        "edition_name": Value::Null,
        "cover_path": Value::Null,
        "tagline": "A Greek-English dictionary built from English Wiktionary with gender, variant forms, etymology, usage examples, cross-reference links, and polytonic lookup support. Inflected forms automatically redirect to their headword.",
        "copyright": {
            "holder": "Open Greek",
            "extra_lines": [],
        },
        "tools": [
            {
                "role": "Dictionary compiled by",
                "name": "Lemma",
                "url": "https://github.com/open-greek/lemma",
                "suffix": ".",
            },
            {
                "role": "MOBI generated by",
                "name": "Kindling",
                "url": "https://github.com/ciscoriordan/kindling",
                "suffix": " by Francisco Riordan.",
            },
        ],
        "data_sources": [
            {
                "name": "Wiktionary",
                "url": "https://en.wiktionary.org/",
                "desc": "dictionary content available under the <a href=\"https://creativecommons.org/licenses/by-sa/4.0/\">Creative Commons Attribution-ShareAlike 4.0 International License</a>. Machine-readable data provided by <a href=\"https://kaikki.org/\">Kaikki.org</a>."
            },
            {
                "name": "Dilemma",
                "url": "https://github.com/open-greek/dilemma",
                "desc": "Greek lemmatizer from the Open Greek project (inflection data)."
            },
            {
                "name": "FrequencyWords",
                "url": "https://github.com/hermitdave/FrequencyWords",
                "desc": "word frequency data from the OpenSubtitles 2018 corpus, MIT License."
            }
        ],
        "features": [
            "31,000+ headwords with 689,000+ inflected lookup forms",
            "Both monotonic and polytonic Greek supported",
            "Part of speech with gender and variant forms (e.g., plural, feminine, neuter)",
            "14,000+ etymologies (transliterations stripped)",
            "5,000+ usage examples with bolded headwords",
            "Cross-reference links between related entries",
        ]
    })
}

fn deep_merge(base: &mut Value, overrides: Value) {
    match (base, overrides) {
        (Value::Object(b), Value::Object(o)) => {
            for (k, v) in o {
                match b.get_mut(&k) {
                    Some(existing) if existing.is_object() && v.is_object() => {
                        deep_merge(existing, v);
                    }
                    _ => {
                        b.insert(k, v);
                    }
                }
            }
        }
        (b, o) => {
            *b = o;
        }
    }
}

pub fn load_front_matter(path: Option<&Path>) -> Result<FrontMatter, Box<dyn std::error::Error>> {
    let mut base = default_front_matter();
    let Some(path) = path else { return Ok(base); };

    let raw = fs::read_to_string(path)?;
    let mut overrides: Value = serde_json::from_str(&raw)?;
    if !overrides.is_object() {
        return Err(format!("Front-matter file {:?} must contain a JSON object", path).into());
    }

    // Resolve relative cover_path against override file directory
    if let Some(obj) = overrides.as_object_mut() {
        if let Some(Value::String(cp)) = obj.get("cover_path").cloned() {
            let cover_path = Path::new(&cp);
            if !cover_path.is_absolute() {
                let parent: PathBuf = path.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| PathBuf::from("."));
                let abs = fs::canonicalize(parent.join(cover_path))
                    .unwrap_or_else(|_| parent.join(cover_path));
                obj.insert("cover_path".to_string(), Value::String(abs.to_string_lossy().into_owned()));
            }
        }
    }

    deep_merge(&mut base, overrides);
    Ok(base)
}

pub fn get_str<'a>(fm: &'a Value, key: &str) -> Option<&'a str> {
    fm.get(key).and_then(|v| v.as_str())
}

pub fn get_object<'a>(fm: &'a Value, key: &str) -> Option<&'a Map<String, Value>> {
    fm.get(key).and_then(|v| v.as_object())
}

pub fn get_array<'a>(fm: &'a Value, key: &str) -> Option<&'a Vec<Value>> {
    fm.get(key).and_then(|v| v.as_array())
}
